"""Homelab agent tools package."""

from .homelab_tools import (add_annotation, analyze_slow_queries,
                            check_adguard_status, check_alert_routing,
                            check_ap_health, check_automation_status,
                            check_blocklist_status, check_container_logs,
                            check_container_status, check_database_locks,
                            check_database_sizes, check_device_connectivity,
                            check_docker_system_health, check_docker_volumes,
                            check_homeassistant_status, check_index_health,
                            check_lxc_logs, check_lxc_network,
                            check_lxc_snapshots, check_lxc_status,
                            check_postgres_health, check_prometheus_rules,
                            check_prometheus_targets, check_prometheus_tsdb,
                            check_proxmox_node_health, check_proxmox_vm_status,
                            check_replication_status, check_security_events,
                            check_specific_database, check_table_bloat,
                            check_wan_connectivity, check_zone_health,
                            clear_postgres_connections, create_alert_silence,
                            create_lxc_snapshot, create_snapshot,
                            delete_alert_silence,
                            get_adguard_protection_summary,
                            get_alertmanager_status, get_cloudflare_analytics,
                            get_cloudflare_status,
                            get_container_resource_usage,
                            get_critical_infrastructure_status, get_dashboard,
                            get_dns_query_stats, get_entity_history,
                            get_entity_state, get_grafana_status,
                            get_homeassistant_summary, get_lxc_config,
                            get_lxc_resource_usage, get_network_performance,
                            get_prometheus_alerts,
                            get_prometheus_config_status,
                            get_prometheus_runtime_info,
                            get_proxmox_cluster_status,
                            get_proxmox_storage_status,
                            get_proxmox_system_summary, inspect_docker_network,
                            list_active_alerts, list_alert_silences,
                            list_cloudflare_zones, list_dashboards,
                            list_datasources, list_docker_images,
                            list_homeassistant_entities, list_lxc_containers,
                            list_proxmox_vms, list_tailscale_devices,
                            list_unifi_devices, monitor_database_connections,
                            monitor_dns_clients, monitor_dns_records,
                            monitor_network_clients, monitor_switch_ports,
                            monitor_vacuum_status, monitor_vpn_health,
                            prune_docker_images, query_database_performance,
                            query_prometheus, restart_container, restart_lxc,
                            restart_postgres_service, send_telegram,
                            update_docker_resources, update_lxc_resources,
                            vacuum_postgres_table)

__all__ = [
    "query_prometheus",
    "check_container_status",
    "restart_container",
    "check_container_logs",
    "check_lxc_status",
    "restart_lxc",
    "send_telegram",
    "list_tailscale_devices",
    "check_device_connectivity",
    "monitor_vpn_health",
    "get_critical_infrastructure_status",
    "check_postgres_health",
    "query_database_performance",
    "check_database_sizes",
    "monitor_database_connections",
    "check_specific_database",
    "check_replication_status",
    "check_table_bloat",
    "analyze_slow_queries",
    "check_index_health",
    "monitor_vacuum_status",
    "check_database_locks",
    "list_unifi_devices",
    "check_ap_health",
    "monitor_network_clients",
    "check_wan_connectivity",
    "monitor_switch_ports",
    "get_network_performance",
    "list_cloudflare_zones",
    "check_zone_health",
    "get_cloudflare_analytics",
    "check_security_events",
    "monitor_dns_records",
    "get_cloudflare_status",
    "check_adguard_status",
    "get_dns_query_stats",
    "check_blocklist_status",
    "monitor_dns_clients",
    "get_adguard_protection_summary",
    "check_proxmox_node_health",
    "list_proxmox_vms",
    "check_proxmox_vm_status",
    "get_proxmox_storage_status",
    "get_proxmox_cluster_status",
    "get_proxmox_system_summary",
    "list_lxc_containers",
    "check_lxc_logs",
    "get_lxc_resource_usage",
    "check_lxc_snapshots",
    "check_lxc_network",
    "get_lxc_config",
    "update_lxc_resources",
    "create_lxc_snapshot",
    "restart_postgres_service",
    "check_homeassistant_status",
    "list_homeassistant_entities",
    "get_entity_state",
    "get_entity_history",
    "check_automation_status",
    "get_homeassistant_summary",
    "check_prometheus_targets",
    "check_prometheus_rules",
    "get_prometheus_alerts",
    "check_prometheus_tsdb",
    "get_prometheus_runtime_info",
    "get_prometheus_config_status",
    "list_docker_images",
    "prune_docker_images",
    "inspect_docker_network",
    "check_docker_volumes",
    "get_container_resource_usage",
    "check_docker_system_health",
    "update_docker_resources",
    "list_active_alerts",
    "list_alert_silences",
    "create_alert_silence",
    "delete_alert_silence",
    "check_alert_routing",
    "get_alertmanager_status",
    "add_annotation",
    "get_grafana_status",
    "list_dashboards",
    "get_dashboard",
    "create_snapshot",
    "list_datasources",
    "check_replication_status",
    "check_table_bloat",
    "analyze_slow_queries",
    "check_index_health",
    "monitor_vacuum_status",
    "check_database_locks",
    "vacuum_postgres_table",
    "clear_postgres_connections",
]
